version: '3'
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

services:
  node:
    container_name: node
    restart: always
    build: .
    volumes:
      - ./src:/usr/app/src
      - /usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    environment:
      PORT: ${PORT}
    networks:
      - default

  database:
    container_name: postgres
    restart: always
    image: postgres:15.3-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - default
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
